version: '3.7'


services:
  paper:
    build: .
    container_name: pikostudio-server
    stdin_open: true
    tty: true
    ports:
      - 25565:25565
      - 5005:5005
    volumes:
      - ./server:/data
    entrypoint:
      - /docker-setup-plugin
      - https://github.com/noonmaru/kotlin-plugin/releases/download/1.4.10/Kotlin.jar
      - https://ci.lucko.me/job/LuckPerms/1232/artifact/bukkit/build/libs/LuckPerms-Bukkit-5.2.67.jar
